Número de condición de una matriz

El número de condición de una matriz se usa para cuantificar su nivel de mal condicionamiento. Es siempre un número mayor que 1, por lo que el sistema Ax = b estará mejor condicionado cuanto más próximo a 1 esté dicho cond(A).

In [81]:
import numpy as np

# x + y = 2
# 1.0001x + y = 2.0001

matriz = np.array([[1,1],[1.0001,1]],dtype=np.float)
constantes = np.array([[2],[2.0001]])
matriz_2 = np.array([[1.1,1],[1.0001,1]],dtype=np.float)    # Matriz con error

In [82]:
# Norma de la matriz 1
norma_inf_matriz_1 = np.linalg.norm(matriz,np.inf)       # Norma de fila
norma_inf_matriz_1

2.0000999999999998


In [83]:
# Norma de la matriz 2
norma_inf_matriz_2 = np.linalg.norm(matriz_2,np.inf)       # Norma de fila
norma_inf_matriz_2

2.1


In [84]:
inversa_1 = np.linalg.inv(matriz)     # Inversa de una matriz
inversa_2 = np.linalg.inv(matriz_2)
print(inversa_1)
print(inversa_2)

[[-10000.  10000.]
 [ 10001. -10000.]]
[[ 10.01001001 -10.01001001]
 [-10.01101101  11.01101101]]


In [92]:
norma_inf_matriz_1 * np.linalg.norm(inversa_1,np.inf) # Número de condición con la norma infinito

40004.000099993355

In [85]:
# Número de condición de la matriz 1

num_condicion_inf = np.linalg.cond(matriz,np.inf)       # Número de condición con la norma infinito
num_condicion_inf

40004.000099993355

In [86]:
# Número de condición de la matriz 2

num_condicion_inf = np.linalg.cond(matriz_2,np.inf)       # Número de condición con la norma infinito
num_condicion_inf

44.1462462462462

In [87]:
# Solución matriz 1
x_1= np.linalg.solve(matriz,constantes)
print("Solución con NumPy: \n",x_1)

Solución con NumPy: 
 [[1.]
 [1.]]


In [88]:
# Solución matriz 2
x_2= np.linalg.solve(matriz_2,constantes)
print("Solución con NumPy: \n",x_2)

Solución con NumPy: 
 [[-1.0010010e-03]
 [ 2.0011011e+00]]


In [89]:
# Error relativo de la solución

norma_solucion_matriz_1 = np.linalg.norm(x_1,np.inf)
norma_solucion_matriz_2 = np.linalg.norm(x_2,np.inf)

error_solucion = (norma_solucion_matriz_1 - norma_solucion_matriz_2)/norma_solucion_matriz_1
np.absolute(error_solucion*100)


100.11011010966595

In [90]:
# Error relativo de la matriz

error_matriz = (norma_inf_matriz_1 - norma_inf_matriz_2) / norma_inf_matriz_1
np.absolute(error_matriz*100)

4.9947502624868925