Número de condición de una matriz

El número de condición de una matriz se usa para cuantificar su nivel de mal condicionamiento. Es siempre un número mayor que 1, por lo que el sistema Ax = b estará mejor condicionado cuanto más próximo a 1 esté dicho cond(A).

In [12]:
import numpy as np
from IPython.display import Latex

# x + y = 2
# 1.0001x + y = 2.0001

matriz = np.array([[1,1/2,1/3],[1/2,1/3,1/4],[1/3,1/4,1/5]],dtype=float)
constantes = np.array([[10],[20],[30]])
# matriz_2 = np.array([[1.1,1],[1.0001,1]],dtype=np.float)    # Matriz con error

In [4]:
# Norma de la matriz 1
norma_inf_matriz_1 = np.linalg.norm(matriz,np.inf)       # Norma de fila
norma_inf_matriz_1

1.8333333333333333

In [83]:
# Norma de la matriz 2
norma_inf_matriz_2 = np.linalg.norm(matriz_2,np.inf)       # Norma de fila
norma_inf_matriz_2

2.1


In [5]:
inversa_1 = np.linalg.inv(matriz)     # Inversa de una matriz
# inversa_2 = np.linalg.inv(matriz_2)
print(inversa_1)
# print(inversa_2)

[[   9.  -36.   30.]
 [ -36.  192. -180.]
 [  30. -180.  180.]]


In [6]:
norma_inf_matriz_1 * np.linalg.norm(inversa_1,np.inf) # Número de condición con la norma infinito

748.0000000000027

In [15]:
# Número de condición de la matriz 1

num_condicion_inf = np.linalg.cond(matriz,np.inf)       # Número de condición con la norma infinito
Latex(str(num_condicion_inf))

<IPython.core.display.Latex object>

$$
$$

In [86]:
# Número de condición de la matriz 2

num_condicion_inf = np.linalg.cond(matriz_2,np.inf)       # Número de condición con la norma infinito
num_condicion_inf

44.1462462462462

In [7]:
# Solución matriz 1
x_1= np.linalg.solve(matriz,constantes)
print("Solución con NumPy: \n",x_1)

Solución con NumPy: 
 [[  270.]
 [-1920.]
 [ 2100.]]


In [8]:
np.linalg.det(matriz)

0.00046296296296296146

In [88]:
# Solución matriz 2
x_2= np.linalg.solve(matriz_2,constantes)
print("Solución con NumPy: \n",x_2)

Solución con NumPy: 
 [[-1.0010010e-03]
 [ 2.0011011e+00]]


In [89]:
# Error relativo de la solución

norma_solucion_matriz_1 = np.linalg.norm(x_1,np.inf)
norma_solucion_matriz_2 = np.linalg.norm(x_2,np.inf)

error_solucion = (norma_solucion_matriz_1 - norma_solucion_matriz_2)/norma_solucion_matriz_1
np.absolute(error_solucion*100)


100.11011010966595

In [90]:
# Error relativo de la matriz

error_matriz = (norma_inf_matriz_1 - norma_inf_matriz_2) / norma_inf_matriz_1
np.absolute(error_matriz*100)

4.9947502624868925