In [121]:
import numpy as np

def gauss_jordan(a, b):
    n_ecuaciones = len(b)

    m_aumentada = np.concatenate([a,b],axis=1)      # axis=1 para que concatene la matriz como una columna

    for e in range(n_ecuaciones):
        m_aumentada[e,e:] = m_aumentada[e,e:] / m_aumentada[e,e]        # Normalizar la fila
        for fila in range(n_ecuaciones):
            if fila !=e:
                m_aumentada[fila,e:] = m_aumentada[fila,e:] - (m_aumentada[fila,e]* m_aumentada[e,e:])      # Reducir las otras filas
    solucion = m_aumentada[:,n_ecuaciones]      # Devuelve la última columna con la solucion de las variables
    return solucion

In [122]:
def matriz_inversa(a, b, c):
    n_ecuaciones = len(b)

    m_aumentada = np.concatenate([a,b,c],axis=1)        # axis=1 para que concatene la matriz como una columna

    for e in range(n_ecuaciones):
        m_aumentada[e,e:] = m_aumentada[e,e:] / m_aumentada[e,e]        # Normalizar la fila
        for fila in range(n_ecuaciones):
            if fila !=e:
                m_aumentada[fila,e:] = m_aumentada[fila,e:] - (m_aumentada[fila,e]* m_aumentada[e,e:])      # Reducir las otras filas
    solucion = m_aumentada[:,n_ecuaciones+1:]       # Devuelve la última columna con la matriz inversa de A
    return solucion

In [123]:
def pasos_gauss_jordan(n):
    pasos=0
    for e in range(n):
        for i in range(n):
            if i != e:
                for j in range(e,n+1):
                    pasos+= 1
    return pasos

In [124]:
pasos_gauss_jordan(10)

585

In [125]:
import time
def tiempo_gauss_jordan(a,b):
    t1= time.process_time()
    gauss_jordan(a,b)
    t2 = time.process_time()
    return(t2-t1)

In [126]:
a = np.array([[4,2,5],[2,5,8],[2,4,3]],dtype=float)
a2 = np.array([[3.9,2,5],[2,5,8],[2,4,3]],dtype=float)      # Arreglo con error, en vez de 4 se tiene 3.9
b = np.array([[18.0],[27.3],[16.2]],dtype=float)
c = np.array([[1,0,0],[0,1,0],[0,0,1]],dtype=float)     # Matriz identidad

if(np.linalg.det(a) != 0):      # Determinante distinto de cero
    x = gauss_jordan(a, b)
    print("Solución: ",x,"\n"+"Pasos para hallar la solución: ",pasos_gauss_jordan(len(b)),"\n"+"Tiempo para solución: ",tiempo_gauss_jordan(a, b))

    x2 = gauss_jordan(a2, b)
    print("\nError en la solución: ",x-x2)

    dot_p = np.dot(a,x)
    print("\nError de redondeo en las constantes: ")
    for i in range(len(b)):
        error = dot_p[i]-b[i]
        print(error)


Solución:  [1.2 2.1 1.8] 
Pasos para hallar la solución:  18 
Tiempo para solución:  0.0002420000000000755

Error en la solución:  [-0.03623446  0.02131439 -0.00426288]

Error de redondeo en las constantes: 
[0.]
[3.55271368e-15]
[0.]


In [127]:
n_solucion= np.linalg.solve(a,b)
print("Solución con NumPy: \n",n_solucion)

Solución con NumPy: 
 [[1.2]
 [2.1]
 [1.8]]


In [128]:
# Matriz inversa con Gauss-Jordan

y = matriz_inversa(a, b, c)
print(y)

print("\n",np.linalg.inv(a))

[[ 0.29310345 -0.24137931  0.15517241]
 [-0.17241379 -0.03448276  0.37931034]
 [ 0.03448276  0.20689655 -0.27586207]]

 [[ 0.29310345 -0.24137931  0.15517241]
 [-0.17241379 -0.03448276  0.37931034]
 [ 0.03448276  0.20689655 -0.27586207]]
